version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  cache:
    image: redis:6.2.1-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  api:
    build: 
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../../:/waldo_api/
    ports:
      - "3001:3000"
    depends_on:
      - db
      - cache
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://cache:6379/0
  web:
    build: ../../${CLIENT_PATH}
    ports:
      - "3000:3000"
    volumes: 
      - ../../${CLIENT_PATH}:/waldo_client
    depends_on:
      - api
volumes:
  db:
  cache:
