version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - waldodb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/waldo-api
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
volumes:
  waldodb:
