version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./storage:/waldo-api/storage
      - ./:/waldo-api
      - bundle_path:/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      BUNDLE_PATH: /bundle
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  db:
  bundle_path:
